Repository geodatagouv/geoplatform, pull requests merged in 2018-12, with the labels that each got.

#88 Upgrade mapping to conform to Open Licence 2.0
  __tests__/lib/metadata/common/licenses.js
  lib/metadata/common/licenses.js
  lib/search/facets.js
Labels: enhancement

#92 Sort consolidated records on desc createdAt
  lib/models/ConsolidatedRecord.js
  lib/search/index.js
Labels: enhancement

#94 Fix service metadata url extraction
  __tests__/lib/metadata/iso/services.js
  lib/metadata/iso/services.js
Labels: bug

#95 Fix coupled resources extraction
  __tests__/lib/metadata/iso/__snapshots__/index.js.snap
  __tests__/lib/metadata/iso/__snapshots__/services.js.snap
  __tests__/lib/metadata/iso/index.js
  __tests__/lib/metadata/iso/services.js
  lib/metadata/iso/services.js
Labels: bug

#96 Retrieve related WFS features from service metadata
  __tests__/lib/utils/feature-types.js
  lib/jobs/consolidate-record/feature-types.js
  lib/jobs/consolidate-record/index.js
  lib/jobs/lookup-wfs/index.js
  lib/models/ConsolidatedRecord.js
  lib/utils/feature-types.js
Labels: enhancement

#97 Allow setting freshness in consolidate record maintenance
  lib/api/controllers/maintenance.js
Labels: enhancement

#98 Fix search default index
  lib/models/ConsolidatedRecord.js
  lib/search/index.js
Labels: bug, performance

#100 Deduplicate and sort downloads for publication
  plugins/publish-to-udata/mapping.js
Labels: enhancement

#104 Fix filetype property in publication mapping
  plugins/publish-to-udata/mapping.js
Labels: bug

#105 Fix publication issues
  plugins/publish-to-udata/geogw.js
  plugins/publish-to-udata/jobs/definition.js
  plugins/publish-to-udata/jobs/udata-sync-one/index.js
  plugins/publish-to-udata/models/Dataset.js
Labels: bug

#106 Update bull manager
  package.json
  plugins/publish-to-udata/models/Dataset.js
  yarn.lock
Labels: bug, dependencies

#107 Prevent udata-sync-all from failing
  plugins/publish-to-udata/jobs/udata-sync-all/index.js
Labels: bug

#108 Update elect-record timeout
  lib/jobs/definition.js
Labels: bug

#109 Update csw-client
  package.json
  yarn.lock
Labels: bug, dependencies

#110 Update catalog metrics rate limit to 15 minutes
  lib/jobs/compute-catalog-metrics/index.js
Labels: enhancement

#117 Fix publication api routes
  lib/api/controllers/publications.js
  lib/api/index.js
  lib/api/routes/publications.js
Labels: bug

#119 Fix publication
  lib/api/controllers/publications.js
Labels: bug

#128 Add req context to sentry errors
  lib/api/index.js
  lib/utils/sentry.js
  plugins/publish-to-udata/app.js
Labels: enhancement
